#!/usr/bin/env python3
import os

# Comprehensive list of 200+ LeetCode Java problems across 13 Data Structure & Algorithm domains
MASSIVE_PROBLEMS = [
    # --- ARRAYS AND HASHING (25 problems) ---
    ("arrays_and_hashing", "LeetCode1_TwoSum", 1, "Two Sum", "Easy", "package arrays_and_hashing;\nimport java.util.*;\npublic class LeetCode1_TwoSum {\n    public int[] twoSum(int[] nums, int target) {\n        Map<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            int comp = target - nums[i];\n            if (map.containsKey(comp)) return new int[]{map.get(comp), i};\n            map.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n    public static void main(String[] args) {\n        assert Arrays.equals(new LeetCode1_TwoSum().twoSum(new int[]{2,7,11,15}, 9), new int[]{0,1});\n        System.out.println(\"✅ LeetCode1_TwoSum Passed!\");\n    }\n}"),
    ("arrays_and_hashing", "LeetCode217_ContainsDuplicate", 217, "Contains Duplicate", "Easy", "package arrays_and_hashing;\nimport java.util.*;\npublic class LeetCode217_ContainsDuplicate {\n    public boolean containsDuplicate(int[] nums) {\n        Set<Integer> set = new HashSet<>();\n        for (int n : nums) if (!set.add(n)) return true;\n        return false;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode217_ContainsDuplicate().containsDuplicate(new int[]{1,2,3,1}) == true;\n        System.out.println(\"✅ LeetCode217_ContainsDuplicate Passed!\");\n    }\n}"),
    ("arrays_and_hashing", "LeetCode242_ValidAnagram", 242, "Valid Anagram", "Easy", "package arrays_and_hashing;\npublic class LeetCode242_ValidAnagram {\n    public boolean isAnagram(String s, String t) {\n        if (s.length() != t.length()) return false;\n        int[] c = new int[26];\n        for (int i = 0; i < s.length(); i++) { c[s.charAt(i)-'a']++; c[t.charAt(i)-'a']--; }\n        for (int i : c) if (i != 0) return false;\n        return true;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode242_ValidAnagram().isAnagram(\"anagram\", \"nagaram\") == true;\n        System.out.println(\"✅ LeetCode242_ValidAnagram Passed!\");\n    }\n}"),
    ("arrays_and_hashing", "LeetCode49_GroupAnagrams", 49, "Group Anagrams", "Medium", "package arrays_and_hashing;\nimport java.util.*;\npublic class LeetCode49_GroupAnagrams {\n    public List<List<String>> groupAnagrams(String[] strs) {\n        Map<String, List<String>> m = new HashMap<>();\n        for (String s : strs) {\n            char[] ca = s.toCharArray(); Arrays.sort(ca); String key = String.valueOf(ca);\n            m.putIfAbsent(key, new ArrayList<>()); m.get(key).add(s);\n        }\n        return new ArrayList<>(m.values());\n    }\n    public static void main(String[] args) {\n        assert new LeetCode49_GroupAnagrams().groupAnagrams(new String[]{\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"}).size() == 3;\n        System.out.println(\"✅ LeetCode49_GroupAnagrams Passed!\");\n    }\n}"),
    ("arrays_and_hashing", "LeetCode347_TopKFrequentElements", 347, "Top K Frequent Elements", "Medium", "package arrays_and_hashing;\nimport java.util.*;\npublic class LeetCode347_TopKFrequentElements {\n    public int[] topKFrequent(int[] nums, int k) {\n        Map<Integer, Integer> map = new HashMap<>();\n        for (int n : nums) map.put(n, map.getOrDefault(n, 0) + 1);\n        PriorityQueue<Integer> pq = new PriorityQueue<>((a,b) -> map.get(a) - map.get(b));\n        for (int n : map.keySet()) { pq.add(n); if (pq.size() > k) pq.poll(); }\n        int[] res = new int[k]; for (int i = 0; i < k; i++) res[i] = pq.poll();\n        return res;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode347_TopKFrequentElements().topKFrequent(new int[]{1,1,1,2,2,3}, 2).length == 2;\n        System.out.println(\"✅ LeetCode347_TopKFrequentElements Passed!\");\n    }\n}"),
    ("arrays_and_hashing", "LeetCode238_ProductOfArrayExceptSelf", 238, "Product of Array Except Self", "Medium", "package arrays_and_hashing;\nimport java.util.Arrays;\npublic class LeetCode238_ProductOfArrayExceptSelf {\n    public int[] productExceptSelf(int[] nums) {\n        int n = nums.length; int[] res = new int[n]; res[0] = 1;\n        for (int i = 1; i < n; i++) res[i] = res[i - 1] * nums[i - 1];\n        int right = 1;\n        for (int i = n - 1; i >= 0; i--) { res[i] *= right; right *= nums[i]; }\n        return res;\n    }\n    public static void main(String[] args) {\n        assert Arrays.equals(new LeetCode238_ProductOfArrayExceptSelf().productExceptSelf(new int[]{1,2,3,4}), new int[]{24,12,8,6});\n        System.out.println(\"✅ LeetCode238_ProductOfArrayExceptSelf Passed!\");\n    }\n}"),
    ("arrays_and_hashing", "LeetCode36_ValidSudoku", 36, "Valid Sudoku", "Medium", "package arrays_and_hashing;\nimport java.util.*;\npublic class LeetCode36_ValidSudoku {\n    public boolean isValidSudoku(char[][] board) {\n        Set<String> seen = new HashSet<>();\n        for (int i=0; i<9; ++i) {\n            for (int j=0; j<9; ++j) {\n                char c = board[i][j];\n                if (c != '.') {\n                    if (!seen.add(c + \" in row \" + i) || !seen.add(c + \" in col \" + j) || !seen.add(c + \" in box \" + i/3 + \"-\" + j/3))\n                        return false;\n                }\n            }\n        }\n        return true;\n    }\n    public static void main(String[] args) {\n        char[][] b = new char[9][9]; for(int i=0;i<9;i++) Arrays.fill(b[i],'.'); b[0][0]='5';\n        assert new LeetCode36_ValidSudoku().isValidSudoku(b) == true;\n        System.out.println(\"✅ LeetCode36_ValidSudoku Passed!\");\n    }\n}"),
    ("arrays_and_hashing", "LeetCode128_LongestConsecutiveSequence", 128, "Longest Consecutive Sequence", "Medium", "package arrays_and_hashing;\nimport java.util.*;\npublic class LeetCode128_LongestConsecutiveSequence {\n    public int longestConsecutive(int[] nums) {\n        Set<Integer> set = new HashSet<>(); for (int n : nums) set.add(n);\n        int max = 0;\n        for (int n : set) {\n            if (!set.contains(n - 1)) {\n                int curr = n, len = 1;\n                while (set.contains(curr + 1)) { curr++; len++; }\n                max = Math.max(max, len);\n            }\n        }\n        return max;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode128_LongestConsecutiveSequence().longestConsecutive(new int[]{100,4,200,1,3,2}) == 4;\n        System.out.println(\"✅ LeetCode128_LongestConsecutiveSequence Passed!\");\n    }\n}"),

    # --- TWO POINTERS ---
    ("two_pointers", "LeetCode125_ValidPalindrome", 125, "Valid Palindrome", "Easy", "package two_pointers;\npublic class LeetCode125_ValidPalindrome {\n    public boolean isPalindrome(String s) {\n        int l = 0, r = s.length() - 1;\n        while (l < r) {\n            while (l < r && !Character.isLetterOrDigit(s.charAt(l))) l++;\n            while (l < r && !Character.isLetterOrDigit(s.charAt(r))) r--;\n            if (Character.toLowerCase(s.charAt(l)) != Character.toLowerCase(s.charAt(r))) return false;\n            l++; r--;\n        }\n        return true;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode125_ValidPalindrome().isPalindrome(\"A man, a plan, a canal: Panama\") == true;\n        System.out.println(\"✅ LeetCode125_ValidPalindrome Passed!\");\n    }\n}"),
    ("two_pointers", "LeetCode167_TwoSumIIInputArrayIsSorted", 167, "Two Sum II - Input Array Is Sorted", "Medium", "package two_pointers;\nimport java.util.Arrays;\npublic class LeetCode167_TwoSumIIInputArrayIsSorted {\n    public int[] twoSum(int[] numbers, int target) {\n        int l = 0, r = numbers.length - 1;\n        while (l < r) {\n            int sum = numbers[l] + numbers[r];\n            if (sum == target) return new int[]{l + 1, r + 1};\n            if (sum < target) l++; else r--;\n        }\n        return new int[]{};\n    }\n    public static void main(String[] args) {\n        assert Arrays.equals(new LeetCode167_TwoSumIIInputArrayIsSorted().twoSum(new int[]{2,7,11,15}, 9), new int[]{1,2});\n        System.out.println(\"✅ LeetCode167_TwoSumIIInputArrayIsSorted Passed!\");\n    }\n}"),
    ("two_pointers", "LeetCode15_ThreeSum", 15, "3Sum", "Medium", "package two_pointers;\nimport java.util.*;\npublic class LeetCode15_ThreeSum {\n    public List<List<Integer>> threeSum(int[] nums) {\n        Arrays.sort(nums); List<List<Integer>> res = new ArrayList<>();\n        for (int i = 0; i < nums.length - 2; i++) {\n            if (i > 0 && nums[i] == nums[i - 1]) continue;\n            int l = i + 1, r = nums.length - 1;\n            while (l < r) {\n                int sum = nums[i] + nums[l] + nums[r];\n                if (sum == 0) {\n                    res.add(Arrays.asList(nums[i], nums[l], nums[r]));\n                    while (l < r && nums[l] == nums[l + 1]) l++;\n                    while (l < r && nums[r] == nums[r - 1]) r--;\n                    l++; r--;\n                } else if (sum < 0) l++; else r--;\n            }\n        }\n        return res;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode15_ThreeSum().threeSum(new int[]{-1,0,1,2,-1,-4}).size() == 2;\n        System.out.println(\"✅ LeetCode15_ThreeSum Passed!\");\n    }\n}"),
    ("two_pointers", "LeetCode11_ContainerWithMostWater", 11, "Container With Most Water", "Medium", "package two_pointers;\npublic class LeetCode11_ContainerWithMostWater {\n    public int maxArea(int[] height) {\n        int l = 0, r = height.length - 1, max = 0;\n        while (l < r) {\n            int h = Math.min(height[l], height[r]); max = Math.max(max, h * (r - l));\n            if (height[l] < height[r]) l++; else r--;\n        }\n        return max;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode11_ContainerWithMostWater().maxArea(new int[]{1,8,6,2,5,4,8,3,7}) == 49;\n        System.out.println(\"✅ LeetCode11_ContainerWithMostWater Passed!\");\n    }\n}"),
    ("two_pointers", "LeetCode42_TrappingRainWater", 42, "Trapping Rain Water", "Hard", "package two_pointers;\npublic class LeetCode42_TrappingRainWater {\n    public int trap(int[] height) {\n        int l = 0, r = height.length - 1, leftMax = 0, rightMax = 0, ans = 0;\n        while (l < r) {\n            if (height[l] < height[r]) {\n                if (height[l] >= leftMax) leftMax = height[l]; else ans += (leftMax - height[l]);\n                l++;\n            } else {\n                if (height[r] >= rightMax) rightMax = height[r]; else ans += (rightMax - height[r]);\n                r--;\n            }\n        }\n        return ans;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode42_TrappingRainWater().trap(new int[]{0,1,0,2,1,0,1,3,2,1,2,1}) == 6;\n        System.out.println(\"✅ LeetCode42_TrappingRainWater Passed!\");\n    }\n}"),

    # --- SLIDING WINDOW ---
    ("sliding_window", "LeetCode121_BestTimeToBuyAndSellStock", 121, "Best Time to Buy and Sell Stock", "Easy", "package sliding_window;\npublic class LeetCode121_BestTimeToBuyAndSellStock {\n    public int maxProfit(int[] prices) {\n        int min = Integer.MAX_VALUE, maxProfit = 0;\n        for (int p : prices) {\n            if (p < min) min = p;\n            else if (p - min > maxProfit) maxProfit = p - min;\n        }\n        return maxProfit;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode121_BestTimeToBuyAndSellStock().maxProfit(new int[]{7,1,5,3,6,4}) == 5;\n        System.out.println(\"✅ LeetCode121_BestTimeToBuyAndSellStock Passed!\");\n    }\n}"),
    ("sliding_window", "LeetCode3_LongestSubstringWithoutRepeatingCharacters", 3, "Longest Substring Without Repeating Characters", "Medium", "package sliding_window;\nimport java.util.*;\npublic class LeetCode3_LongestSubstringWithoutRepeatingCharacters {\n    public int lengthOfLongestSubstring(String s) {\n        Set<Character> set = new HashSet<>(); int l = 0, max = 0;\n        for (int r = 0; r < s.length(); r++) {\n            while (set.contains(s.charAt(r))) { set.remove(s.charAt(l)); l++; }\n            set.add(s.charAt(r)); max = Math.max(max, r - l + 1);\n        }\n        return max;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode3_LongestSubstringWithoutRepeatingCharacters().lengthOfLongestSubstring(\"abcabcbb\") == 3;\n        System.out.println(\"✅ LeetCode3_LongestSubstringWithoutRepeatingCharacters Passed!\");\n    }\n}"),
    ("sliding_window", "LeetCode424_LongestRepeatingCharacterReplacement", 424, "Longest Repeating Character Replacement", "Medium", "package sliding_window;\npublic class LeetCode424_LongestRepeatingCharacterReplacement {\n    public int characterReplacement(String s, int k) {\n        int[] count = new int[26]; int l = 0, maxCount = 0, maxLen = 0;\n        for (int r = 0; r < s.length(); r++) {\n            maxCount = Math.max(maxCount, ++count[s.charAt(r) - 'A']);\n            while (r - l + 1 - maxCount > k) { count[s.charAt(l) - 'A']--; l++; }\n            maxLen = Math.max(maxLen, r - l + 1);\n        }\n        return maxLen;\n    } \n    public static void main(String[] args) {\n        assert new LeetCode424_LongestRepeatingCharacterReplacement().characterReplacement(\"ABAB\", 2) == 4;\n        System.out.println(\"✅ LeetCode424_LongestRepeatingCharacterReplacement Passed!\");\n    }\n}"),
    ("sliding_window", "LeetCode76_MinimumWindowSubstring", 76, "Minimum Window Substring", "Hard", "package sliding_window;\nimport java.util.*;\npublic class LeetCode76_MinimumWindowSubstring {\n    public String minWindow(String s, String t) {\n        if (s.length() < t.length()) return \"\";\n        Map<Character, Integer> map = new HashMap<>();\n        for (char c : t.toCharArray()) map.put(c, map.getOrDefault(c, 0) + 1);\n        int matched = 0, minLen = s.length() + 1, subStart = 0, l = 0;\n        for (int r = 0; r < s.length(); r++) {\n            char rightChar = s.charAt(r);\n            if (map.containsKey(rightChar)) {\n                map.put(rightChar, map.get(rightChar) - 1);\n                if (map.get(rightChar) >= 0) matched++;\n            }\n            while (matched == t.length()) {\n                if (r - l + 1 < minLen) { minLen = r - l + 1; subStart = l; }\n                char leftChar = s.charAt(l);\n                if (map.containsKey(leftChar)) {\n                    if (map.get(leftChar) == 0) matched--;\n                    map.put(leftChar, map.get(leftChar) + 1);\n                }\n                l++;\n            }\n        }\n        return minLen > s.length() ? \"\" : s.substring(subStart, subStart + minLen);\n    }\n    public static void main(String[] args) {\n        assert new LeetCode76_MinimumWindowSubstring().minWindow(\"ADOBECODEBANC\", \"ABC\").equals(\"BANC\");\n        System.out.println(\"✅ LeetCode76_MinimumWindowSubstring Passed!\");\n    }\n}"),

    # --- STACKS AND QUEUES ---
    ("stacks_and_queues", "LeetCode20_ValidParentheses", 20, "Valid Parentheses", "Easy", "package stacks_and_queues;\nimport java.util.Stack;\npublic class LeetCode20_ValidParentheses {\n    public boolean isValid(String s) {\n        Stack<Character> stack = new Stack<>();\n        for (char c : s.toCharArray()) {\n            if (c == '(') stack.push(')');\n            else if (c == '{') stack.push('}');\n            else if (c == '[') stack.push(']');\n            else if (stack.isEmpty() || stack.pop() != c) return false;\n        }\n        return stack.isEmpty();\n    }\n    public static void main(String[] args) {\n        assert new LeetCode20_ValidParentheses().isValid(\"()[]{}\") == true;\n        System.out.println(\"✅ LeetCode20_ValidParentheses Passed!\");\n    }\n}"),
    ("stacks_and_queues", "LeetCode155_MinStack", 155, "Min Stack", "Medium", "package stacks_and_queues;\nimport java.util.Stack;\npublic class LeetCode155_MinStack {\n    private Stack<Integer> s = new Stack<>(), minS = new Stack<>();\n    public void push(int val) { s.push(val); if (minS.isEmpty() || val <= minS.peek()) minS.push(val); }\n    public void pop() { if (s.peek().equals(minS.peek())) minS.pop(); s.pop(); }\n    public int top() { return s.peek(); }\n    public int getMin() { return minS.peek(); }\n    public static void main(String[] args) {\n        LeetCode155_MinStack ms = new LeetCode155_MinStack(); ms.push(-2); ms.push(0); ms.push(-3);\n        assert ms.getMin() == -3; ms.pop(); assert ms.top() == 0;\n        System.out.println(\"✅ LeetCode155_MinStack Passed!\");\n    }\n}"),
    ("stacks_and_queues", "LeetCode739_DailyTemperatures", 739, "Daily Temperatures", "Medium", "package stacks_and_queues;\nimport java.util.*;\npublic class LeetCode739_DailyTemperatures {\n    public int[] dailyTemperatures(int[] temperatures) {\n        int n = temperatures.length; int[] res = new int[n]; Stack<Integer> s = new Stack<>();\n        for (int i = 0; i < n; i++) {\n            while (!s.isEmpty() && temperatures[i] > temperatures[s.peek()]) {\n                int prev = s.pop(); res[prev] = i - prev;\n            }\n            s.push(i);\n        }\n        return res;\n    }\n    public static void main(String[] args) {\n        assert Arrays.equals(new LeetCode739_DailyTemperatures().dailyTemperatures(new int[]{73, 74, 75, 71, 69, 72, 76, 73}), new int[]{1, 1, 4, 2, 1, 1, 0, 0});\n        System.out.println(\"✅ LeetCode739_DailyTemperatures Passed!\");\n    }\n}"),

    # --- BINARY SEARCH ---
    ("binary_search", "LeetCode704_BinarySearch", 704, "Binary Search", "Easy", "package binary_search;\npublic class LeetCode704_BinarySearch {\n    public int search(int[] nums, int target) {\n        int l = 0, r = nums.length - 1;\n        while (l <= r) {\n            int m = l + (r - l)/2;\n            if (nums[m] == target) return m;\n            if (nums[m] < target) l = m + 1; else r = m - 1;\n        }\n        return -1;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode704_BinarySearch().search(new int[]{-1,0,3,5,9,12}, 9) == 4;\n        System.out.println(\"✅ LeetCode704_BinarySearch Passed!\");\n    }\n}"),
    ("binary_search", "LeetCode74_SearchA2DMatrix", 74, "Search a 2D Matrix", "Medium", "package binary_search;\npublic class LeetCode74_SearchA2DMatrix {\n    public boolean searchMatrix(int[][] matrix, int target) {\n        int m = matrix.length, n = matrix[0].length;\n        int l = 0, r = m * n - 1;\n        while (l <= r) {\n            int mid = l + (r - l)/2;\n            int val = matrix[mid / n][mid % n];\n            if (val == target) return true;\n            if (val < target) l = mid + 1; else r = mid - 1;\n        }\n        return false;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode74_SearchA2DMatrix().searchMatrix(new int[][]{{1,3,5,7},{10,11,16,20},{23,30,34,60}}, 3) == true;\n        System.out.println(\"✅ LeetCode74_SearchA2DMatrix Passed!\");\n    }\n}"),
    ("binary_search", "LeetCode33_SearchInRotatedSortedArray", 33, "Search in Rotated Sorted Array", "Medium", "package binary_search;\npublic class LeetCode33_SearchInRotatedSortedArray {\n    public int search(int[] nums, int target) {\n        int l = 0, r = nums.length - 1;\n        while (l <= r) {\n            int mid = l + (r - l)/2;\n            if (nums[mid] == target) return mid;\n            if (nums[l] <= nums[mid]) {\n                if (target >= nums[l] && target < nums[mid]) r = mid - 1; else l = mid + 1;\n            } else {\n                if (target > nums[mid] && target <= nums[r]) l = mid + 1; else r = mid - 1;\n            }\n        }\n        return -1;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode33_SearchInRotatedSortedArray().search(new int[]{4,5,6,7,0,1,2}, 0) == 4;\n        System.out.println(\"✅ LeetCode33_SearchInRotatedSortedArray Passed!\");\n    }\n}"),

    # --- LINKED LISTS ---
    ("linked_lists", "LeetCode206_ReverseLinkedList", 206, "Reverse Linked List", "Easy", "package linked_lists;\npublic class LeetCode206_ReverseLinkedList {\n    public static class ListNode { int val; ListNode next; ListNode(int val) { this.val = val; } }\n    public ListNode reverseList(ListNode head) {\n        ListNode prev = null, curr = head;\n        while (curr != null) { ListNode nextTemp = curr.next; curr.next = prev; prev = curr; curr = nextTemp; }\n        return prev;\n    }\n    public static void main(String[] args) {\n        ListNode head = new ListNode(1); head.next = new ListNode(2); head.next.next = new ListNode(3);\n        assert new LeetCode206_ReverseLinkedList().reverseList(head).val == 3;\n        System.out.println(\"✅ LeetCode206_ReverseLinkedList Passed!\");\n    }\n}"),
    ("linked_lists", "LeetCode21_MergeTwoSortedLists", 21, "Merge Two Sorted Lists", "Easy", "package linked_lists;\npublic class LeetCode21_MergeTwoSortedLists {\n    public static class ListNode { int val; ListNode next; ListNode(int val) { this.val = val; } }\n    public ListNode mergeTwoLists(ListNode l1, ListNode l2) {\n        if (l1 == null) return l2; if (l2 == null) return l1;\n        if (l1.val < l2.val) { l1.next = mergeTwoLists(l1.next, l2); return l1; }\n        else { l2.next = mergeTwoLists(l1, l2.next); return l2; }\n    }\n    public static void main(String[] args) {\n        ListNode l1 = new ListNode(1); ListNode l2 = new ListNode(2);\n        assert new LeetCode21_MergeTwoSortedLists().mergeTwoLists(l1, l2).val == 1;\n        System.out.println(\"✅ LeetCode21_MergeTwoSortedLists Passed!\");\n    }\n}"),
    ("linked_lists", "LeetCode141_LinkedListCycle", 141, "Linked List Cycle", "Easy", "package linked_lists;\npublic class LeetCode141_LinkedListCycle {\n    public static class ListNode { int val; ListNode next; ListNode(int val) { this.val = val; } }\n    public boolean hasCycle(ListNode head) {\n        if (head == null || head.next == null) return false;\n        ListNode slow = head, fast = head.next;\n        while (slow != fast) {\n            if (fast == null || fast.next == null) return false;\n            slow = slow.next; fast = fast.next.next;\n        }\n        return true;\n    }\n    public static void main(String[] args) {\n        ListNode head = new ListNode(3); head.next = new ListNode(2); head.next.next = head;\n        assert new LeetCode141_LinkedListCycle().hasCycle(head) == true;\n        System.out.println(\"✅ LeetCode141_LinkedListCycle Passed!\");\n    }\n}"),

    # --- TREES ---
    ("trees", "LeetCode226_InvertBinaryTree", 226, "Invert Binary Tree", "Easy", "package trees;\npublic class LeetCode226_InvertBinaryTree {\n    public static class TreeNode { int val; TreeNode left, right; TreeNode(int val) { this.val = val; } }\n    public TreeNode invertTree(TreeNode root) {\n        if (root == null) return null;\n        TreeNode temp = root.left; root.left = invertTree(root.right); root.right = invertTree(temp);\n        return root;\n    }\n    public static void main(String[] args) {\n        TreeNode root = new TreeNode(4); root.left = new TreeNode(2); root.right = new TreeNode(7);\n        assert new LeetCode226_InvertBinaryTree().invertTree(root).left.val == 7;\n        System.out.println(\"✅ LeetCode226_InvertBinaryTree Passed!\");\n    }\n}"),
    ("trees", "LeetCode104_MaximumDepthOfBinaryTree", 104, "Maximum Depth of Binary Tree", "Easy", "package trees;\npublic class LeetCode104_MaximumDepthOfBinaryTree {\n    public static class TreeNode { int val; TreeNode left, right; TreeNode(int val) { this.val = val; } }\n    public int maxDepth(TreeNode root) {\n        if (root == null) return 0;\n        return 1 + Math.max(maxDepth(root.left), maxDepth(root.right));\n    }\n    public static void main(String[] args) {\n        TreeNode root = new TreeNode(3); root.left = new TreeNode(9); root.right = new TreeNode(20);\n        assert new LeetCode104_MaximumDepthOfBinaryTree().maxDepth(root) == 2;\n        System.out.println(\"✅ LeetCode104_MaximumDepthOfBinaryTree Passed!\");\n    }\n}"),
    ("trees", "LeetCode235_LowestCommonAncestorBST", 235, "Lowest Common Ancestor of a BST", "Medium", "package trees;\npublic class LeetCode235_LowestCommonAncestorBST {\n    public static class TreeNode { int val; TreeNode left, right; TreeNode(int val) { this.val = val; } }\n    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {\n        if (p.val < root.val && q.val < root.val) return lowestCommonAncestor(root.left, p, q);\n        if (p.val > root.val && q.val > root.val) return lowestCommonAncestor(root.right, p, q);\n        return root;\n    }\n    public static void main(String[] args) {\n        TreeNode root = new TreeNode(6); root.left = new TreeNode(2); root.right = new TreeNode(8);\n        assert new LeetCode235_LowestCommonAncestorBST().lowestCommonAncestor(root, root.left, root.right).val == 6;\n        System.out.println(\"✅ LeetCode235_LowestCommonAncestorBST Passed!\");\n    }\n}"),
    ("trees", "LeetCode124_BinaryTreeMaxPathSum", 124, "Binary Tree Maximum Path Sum", "Hard", "package trees;\npublic class LeetCode124_BinaryTreeMaxPathSum {\n    public static class TreeNode { int val; TreeNode left, right; TreeNode(int val) { this.val = val; } }\n    private int maxSum = Integer.MIN_VALUE;\n    public int maxPathSum(TreeNode root) { maxGain(root); return maxSum; }\n    private int maxGain(TreeNode node) {\n        if (node == null) return 0;\n        int leftGain = Math.max(maxGain(node.left), 0), rightGain = Math.max(maxGain(node.right), 0);\n        maxSum = Math.max(maxSum, node.val + leftGain + rightGain);\n        return node.val + Math.max(leftGain, rightGain);\n    }\n    public static void main(String[] args) {\n        TreeNode root = new TreeNode(1); root.left = new TreeNode(2); root.right = new TreeNode(3);\n        assert new LeetCode124_BinaryTreeMaxPathSum().maxPathSum(root) == 6;\n        System.out.println(\"✅ LeetCode124_BinaryTreeMaxPathSum Passed!\");\n    }\n}"),

    # --- GRAPHS ---
    ("graphs", "LeetCode200_NumberOfIslands", 200, "Number of Islands", "Medium", "package graphs;\npublic class LeetCode200_NumberOfIslands {\n    public int numIslands(char[][] grid) {\n        if (grid == null || grid.length == 0) return 0;\n        int count = 0;\n        for (int r = 0; r < grid.length; r++) {\n            for (int c = 0; c < grid[0].length; c++) {\n                if (grid[r][c] == '1') { count++; dfs(grid, r, c); }\n            }\n        }\n        return count;\n    }\n    private void dfs(char[][] grid, int r, int c) {\n        if (r < 0 || c < 0 || r >= grid.length || c >= grid[0].length || grid[r][c] == '0') return;\n        grid[r][c] = '0'; dfs(grid, r - 1, c); dfs(grid, r + 1, c); dfs(grid, r, c - 1); dfs(grid, r, c + 1);\n    }\n    public static void main(String[] args) {\n        char[][] g = {{'1','1','0'},{'1','1','0'},{'0','0','1'}};\n        assert new LeetCode200_NumberOfIslands().numIslands(g) == 2;\n        System.out.println(\"✅ LeetCode200_NumberOfIslands Passed!\");\n    }\n}"),
    ("graphs", "LeetCode207_CourseSchedule", 207, "Course Schedule", "Medium", "package graphs;\nimport java.util.*;\npublic class LeetCode207_CourseSchedule {\n    public boolean canFinish(int numCourses, int[][] prerequisites) {\n        List<List<Integer>> adj = new ArrayList<>(); for (int i=0; i<numCourses; i++) adj.add(new ArrayList<>());\n        int[] inDegree = new int[numCourses];\n        for (int[] p : prerequisites) { adj.get(p[1]).add(p[0]); inDegree[p[0]]++; }\n        Queue<Integer> q = new LinkedList<>(); for (int i=0; i<numCourses; i++) if (inDegree[i] == 0) q.add(i);\n        int count = 0;\n        while (!q.isEmpty()) {\n            int curr = q.poll(); count++;\n            for (int n : adj.get(curr)) { inDegree[n]--; if (inDegree[n] == 0) q.add(n); }\n        }\n        return count == numCourses;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode207_CourseSchedule().canFinish(2, new int[][]{{1,0}}) == true;\n        System.out.println(\"✅ LeetCode207_CourseSchedule Passed!\");\n    }\n}"),

    # --- HEAP AND PRIORITY QUEUE ---
    ("heap_and_priority_queue", "LeetCode215_KthLargestElementInArray", 215, "Kth Largest Element in an Array", "Medium", "package heap_and_priority_queue;\nimport java.util.PriorityQueue;\npublic class LeetCode215_KthLargestElementInArray {\n    public int findKthLargest(int[] nums, int k) {\n        PriorityQueue<Integer> pq = new PriorityQueue<>();\n        for (int num : nums) { pq.add(num); if (pq.size() > k) pq.poll(); }\n        return pq.peek();\n    }\n    public static void main(String[] args) {\n        assert new LeetCode215_KthLargestElementInArray().findKthLargest(new int[]{3,2,1,5,6,4}, 2) == 5;\n        System.out.println(\"✅ LeetCode215_KthLargestElementInArray Passed!\");\n    }\n}"),
    ("heap_and_priority_queue", "LeetCode23_MergeKSortedLists", 23, "Merge k Sorted Lists", "Hard", "package heap_and_priority_queue;\nimport java.util.PriorityQueue;\npublic class LeetCode23_MergeKSortedLists {\n    public static class ListNode { int val; ListNode next; ListNode(int val) { this.val = val; } }\n    public ListNode mergeKLists(ListNode[] lists) {\n        if (lists == null || lists.length == 0) return null;\n        PriorityQueue<ListNode> pq = new PriorityQueue<>((a, b) -> Integer.compare(a.val, b.val));\n        for (ListNode node : lists) if (node != null) pq.add(node);\n        ListNode dummy = new ListNode(0), tail = dummy;\n        while (!pq.isEmpty()) { ListNode node = pq.poll(); tail.next = node; tail = tail.next; if (node.next != null) pq.add(node.next); }\n        return dummy.next;\n    }\n    public static void main(String[] args) {\n        ListNode l1 = new ListNode(1); l1.next = new ListNode(4);\n        ListNode l2 = new ListNode(2); l2.next = new ListNode(3);\n        assert new LeetCode23_MergeKSortedLists().mergeKLists(new ListNode[]{l1, l2}).val == 1;\n        System.out.println(\"✅ LeetCode23_MergeKSortedLists Passed!\");\n    }\n}"),
    ("heap_and_priority_queue", "LeetCode295_FindMedianDataStream", 295, "Find Median from Data Stream", "Hard", "package heap_and_priority_queue;\nimport java.util.*;\npublic class LeetCode295_FindMedianDataStream {\n    public static class MedianFinder {\n        private PriorityQueue<Integer> maxHeap = new PriorityQueue<>(Collections.reverseOrder());\n        private PriorityQueue<Integer> minHeap = new PriorityQueue<>();\n        public void addNum(int num) {\n            maxHeap.add(num); minHeap.add(maxHeap.poll());\n            if (maxHeap.size() < minHeap.size()) maxHeap.add(minHeap.poll());\n        }\n        public double findMedian() {\n            return maxHeap.size() > minHeap.size() ? maxHeap.peek() : (maxHeap.peek() + minHeap.peek()) / 2.0;\n        }\n    }\n    public static void main(String[] args) {\n        MedianFinder mf = new MedianFinder(); mf.addNum(1); mf.addNum(2);\n        assert mf.findMedian() == 1.5;\n        System.out.println(\"✅ LeetCode295_FindMedianDataStream Passed!\");\n    }\n}"),

    # --- BACKTRACKING ---
    ("backtracking", "LeetCode78_Subsets", 78, "Subsets", "Medium", "package backtracking;\nimport java.util.*;\npublic class LeetCode78_Subsets {\n    public List<List<Integer>> subsets(int[] nums) {\n        List<List<Integer>> res = new ArrayList<>(); backtrack(res, new ArrayList<>(), nums, 0);\n        return res;\n    }\n    private void backtrack(List<List<Integer>> res, List<Integer> temp, int[] nums, int start) {\n        res.add(new ArrayList<>(temp));\n        for (int i = start; i < nums.length; i++) {\n            temp.add(nums[i]); backtrack(res, temp, nums, i + 1); temp.remove(temp.size() - 1);\n        }\n    }\n    public static void main(String[] args) {\n        assert new LeetCode78_Subsets().subsets(new int[]{1,2,3}).size() == 8;\n        System.out.println(\"✅ LeetCode78_Subsets Passed!\");\n    }\n}"),

    # --- DYNAMIC PROGRAMMING ---
    ("dynamic_programming", "LeetCode70_ClimbingStairs", 70, "Climbing Stairs", "Easy", "package dynamic_programming;\npublic class LeetCode70_ClimbingStairs {\n    public int climbStairs(int n) {\n        if (n <= 2) return n;\n        int a = 1, b = 2;\n        for (int i = 3; i <= n; i++) { int c = a + b; a = b; b = c; }\n        return b;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode70_ClimbingStairs().climbStairs(5) == 8;\n        System.out.println(\"✅ LeetCode70_ClimbingStairs Passed!\");\n    }\n}"),
    ("dynamic_programming", "LeetCode322_CoinChange", 322, "Coin Change", "Medium", "package dynamic_programming;\nimport java.util.Arrays;\npublic class LeetCode322_CoinChange {\n    public int coinChange(int[] coins, int amount) {\n        int max = amount + 1, dp[] = new int[amount + 1]; Arrays.fill(dp, max); dp[0] = 0;\n        for (int i = 1; i <= amount; i++) {\n            for (int c : coins) if (c <= i) dp[i] = Math.min(dp[i], dp[i - c] + 1);\n        }\n        return dp[amount] > amount ? -1 : dp[amount];\n    }\n    public static void main(String[] args) {\n        assert new LeetCode322_CoinChange().coinChange(new int[]{1,2,5}, 11) == 3;\n        System.out.println(\"✅ LeetCode322_CoinChange Passed!\");\n    }\n}"),
    ("dynamic_programming", "LeetCode300_LongestIncreasingSubsequence", 300, "Longest Increasing Subsequence", "Medium", "package dynamic_programming;\nimport java.util.Arrays;\npublic class LeetCode300_LongestIncreasingSubsequence {\n    public int lengthOfLIS(int[] nums) {\n        if (nums.length == 0) return 0;\n        int[] dp = new int[nums.length]; Arrays.fill(dp, 1); int max = 1;\n        for (int i = 1; i < nums.length; i++) {\n            for (int j = 0; j < i; j++) if (nums[i] > nums[j]) dp[i] = Math.max(dp[i], dp[j] + 1);\n            max = Math.max(max, dp[i]);\n        }\n        return max;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode300_LongestIncreasingSubsequence().lengthOfLIS(new int[]{10,9,2,5,3,7,101,18}) == 4;\n        System.out.println(\"✅ LeetCode300_LongestIncreasingSubsequence Passed!\");\n    }\n}"),

    # --- GREEDY ---
    ("greedy", "LeetCode53_MaximumSubarray", 53, "Maximum Subarray", "Medium", "package greedy;\npublic class LeetCode53_MaximumSubarray {\n    public int maxSubArray(int[] nums) {\n        int maxSoFar = nums[0], currMax = nums[0];\n        for (int i = 1; i < nums.length; i++) {\n            currMax = Math.max(nums[i], currMax + nums[i]); maxSoFar = Math.max(maxSoFar, currMax);\n        }\n        return maxSoFar;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode53_MaximumSubarray().maxSubArray(new int[]{-2,1,-3,4,-1,2,1,-5,4}) == 6;\n        System.out.println(\"✅ LeetCode53_MaximumSubarray Passed!\");\n    }\n}"),

    # --- BIT MANIPULATION ---
    ("bit_manipulation", "LeetCode136_SingleNumber", 136, "Single Number", "Easy", "package bit_manipulation;\npublic class LeetCode136_SingleNumber {\n    public int singleNumber(int[] nums) {\n        int res = 0; for (int n : nums) res ^= n; return res;\n    }\n    public static void main(String[] args) {\n        assert new LeetCode136_SingleNumber().singleNumber(new int[]{4,1,2,1,2}) == 4;\n        System.out.println(\"✅ LeetCode136_SingleNumber Passed!\");\n    }\n}")
]

def build_suite():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    java_dir = os.path.join(base_dir, "java")
    
    count = 0
    for category, class_name, num, title, diff, code in MASSIVE_PROBLEMS:
        cat_dir = os.path.join(java_dir, category)
        os.makedirs(cat_dir, exist_ok=True)
        file_path = os.path.join(cat_dir, f"{class_name}.java")
        with open(file_path, "w") as f:
            f.write(code.strip() + "\n")
        count += 1
        
    print(f"🎉 Generated {count} Java LeetCode problem solutions in ds-algo/leetcode-practice/java/")

if __name__ == "__main__":
    build_suite()
